'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5472
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", ConfigurationName:="IPaymentGatewayService")> _
Public Interface IPaymentGatewayService

    'CODEGEN: Generating message contract since the wrapper name (AuthorizeRequest) of message AuthorizeRequest does not match the default value (Authorize)
    <System.ServiceModel.OperationContractAttribute(Action:="Authorize", ReplyAction:="Authorize"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function Authorize(ByVal request As AuthorizeRequest) As AuthorizeResponse

    'CODEGEN: Generating message contract since the wrapper name (CaptureRequest) of message CaptureRequest does not match the default value (Capture)
    <System.ServiceModel.OperationContractAttribute(Action:="Capture", ReplyAction:="Capture"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function Capture(ByVal request As CaptureRequest) As CaptureResponse

    'CODEGEN: Generating message contract since the wrapper name (PaymentRequest) of message PaymentRequest does not match the default value (Payment)
    <System.ServiceModel.OperationContractAttribute(Action:="Payment", ReplyAction:="Payment"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function Payment(ByVal request As PaymentRequest) As PaymentResponse

    'CODEGEN: Generating message contract since the wrapper name (RefundRequest) of message RefundRequest does not match the default value (Refund)
    <System.ServiceModel.OperationContractAttribute(Action:="Refund", ReplyAction:="Refund"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function Refund(ByVal request As RefundRequest) As RefundResponse

    'CODEGEN: Generating message contract since the wrapper name (VoidRequest) of message VoidRequest does not match the default value (Void)
    <System.ServiceModel.OperationContractAttribute(Action:="Void", ReplyAction:="Void"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function Void(ByVal request As VoidRequest) As VoidResponse

    'CODEGEN: Generating message contract since the wrapper name (Secure3DLookupRequest) of message Secure3DLookupRequest does not match the default value (Secure3DLookup)
    <System.ServiceModel.OperationContractAttribute(Action:="Secure3DLookup", ReplyAction:="Secure3DLookup"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function Secure3DLookup(ByVal request As Secure3DLookupRequest) As Secure3DLookupResponse
End Interface

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Partial Public Class MessageHeader

    Private messageDateTimeField As System.Nullable(Of Date)

    Private messageDateTimeFieldSpecified As Boolean

    Private messageIDField As String

    Private channelField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=0)> _
    Public Property MessageDateTime() As System.Nullable(Of Date)
        Get
            Return Me.messageDateTimeField
        End Get
        Set(value As System.Nullable(Of Date))
            Me.messageDateTimeField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property MessageDateTimeSpecified() As Boolean
        Get
            Return Me.messageDateTimeFieldSpecified
        End Get
        Set(value As Boolean)
            Me.messageDateTimeFieldSpecified = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=1)> _
    Public Property MessageID() As String
        Get
            Return Me.messageIDField
        End Get
        Set(value As String)
            Me.messageIDField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=2)> _
    Public Property Channel() As String
        Get
            Return Me.channelField
        End Get
        Set(value As String)
            Me.channelField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Partial Public Class ResponseDetail

    Private sourceField As String

    Private codeField As String

    Private descriptionField As String

    Private clientMessageField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
    Public Property Source() As String
        Get
            Return Me.sourceField
        End Get
        Set(value As String)
            Me.sourceField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
    Public Property Code() As String
        Get
            Return Me.codeField
        End Get
        Set(value As String)
            Me.codeField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
    Public Property Description() As String
        Get
            Return Me.descriptionField
        End Get
        Set(value As String)
            Me.descriptionField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
    Public Property ClientMessage() As String
        Get
            Return Me.clientMessageField
        End Get
        Set(value As String)
            Me.clientMessageField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Partial Public Class Address

    Private addressLine1Field As String

    Private addressLine2Field As String

    Private cityField As String

    Private neighbourhoodField As String

    Private postCodeField As String

    Private regionField As String

    Private countryCodeField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=0)> _
    Public Property AddressLine1() As String
        Get
            Return Me.addressLine1Field
        End Get
        Set(value As String)
            Me.addressLine1Field = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=1)> _
    Public Property AddressLine2() As String
        Get
            Return Me.addressLine2Field
        End Get
        Set(value As String)
            Me.addressLine2Field = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=2)> _
    Public Property City() As String
        Get
            Return Me.cityField
        End Get
        Set(value As String)
            Me.cityField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=3)> _
    Public Property Neighbourhood() As String
        Get
            Return Me.neighbourhoodField
        End Get
        Set(value As String)
            Me.neighbourhoodField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=4)> _
    Public Property PostCode() As String
        Get
            Return Me.postCodeField
        End Get
        Set(value As String)
            Me.postCodeField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=5)> _
    Public Property Region() As String
        Get
            Return Me.regionField
        End Get
        Set(value As String)
            Me.regionField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=6)> _
    Public Property CountryCode() As String
        Get
            Return Me.countryCodeField
        End Get
        Set(value As String)
            Me.countryCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Partial Public Class BankCard

    Private tokenField As String

    Private cardAssociationField As String

    Private cardTypeField As System.Nullable(Of BankCardType)

    Private cardTypeFieldSpecified As Boolean

    Private cardholderNameField As String

    Private cardNumberField As String

    Private expiryMonthField As System.Nullable(Of Integer)

    Private expiryMonthFieldSpecified As Boolean

    Private expiryYearField As System.Nullable(Of Integer)

    Private expiryYearFieldSpecified As Boolean

    Private securityCodeField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=0)> _
    Public Property Token() As String
        Get
            Return Me.tokenField
        End Get
        Set(value As String)
            Me.tokenField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=1)> _
    Public Property CardAssociation() As String
        Get
            Return Me.cardAssociationField
        End Get
        Set(value As String)
            Me.cardAssociationField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=2)> _
    Public Property CardType() As System.Nullable(Of BankCardType)
        Get
            Return Me.cardTypeField
        End Get
        Set(value As System.Nullable(Of BankCardType))
            Me.cardTypeField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property CardTypeSpecified() As Boolean
        Get
            Return Me.cardTypeFieldSpecified
        End Get
        Set(value As Boolean)
            Me.cardTypeFieldSpecified = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=3)> _
    Public Property CardholderName() As String
        Get
            Return Me.cardholderNameField
        End Get
        Set(value As String)
            Me.cardholderNameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=4)> _
    Public Property CardNumber() As String
        Get
            Return Me.cardNumberField
        End Get
        Set(value As String)
            Me.cardNumberField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=5)> _
    Public Property ExpiryMonth() As System.Nullable(Of Integer)
        Get
            Return Me.expiryMonthField
        End Get
        Set(value As System.Nullable(Of Integer))
            Me.expiryMonthField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ExpiryMonthSpecified() As Boolean
        Get
            Return Me.expiryMonthFieldSpecified
        End Get
        Set(value As Boolean)
            Me.expiryMonthFieldSpecified = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=6)> _
    Public Property ExpiryYear() As System.Nullable(Of Integer)
        Get
            Return Me.expiryYearField
        End Get
        Set(value As System.Nullable(Of Integer))
            Me.expiryYearField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ExpiryYearSpecified() As Boolean
        Get
            Return Me.expiryYearFieldSpecified
        End Get
        Set(value As Boolean)
            Me.expiryYearFieldSpecified = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True, Order:=7)> _
    Public Property SecurityCode() As String
        Get
            Return Me.securityCodeField
        End Get
        Set(value As String)
            Me.securityCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Public Enum BankCardType

    '''<remarks/>
    Credit

    '''<remarks/>
    Debit
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Public Enum PaymentServiceType

    '''<remarks/>
    CardNotPresent

    '''<remarks/>
    CardNotPresentMoto

    '''<remarks/>
    CardNotPresentBatch

    '''<remarks/>
    PayD
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Public Enum BankAccountType

    '''<remarks/>
    Credit

    '''<remarks/>
    Debit
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
Public Enum TransactionStatusType

    '''<remarks/>
    Success

    '''<remarks/>
    Failure
End Enum

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="AuthorizeRequest", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class AuthorizeRequest

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public MerchantID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2)> _
    Public PreviousTransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public Amount As Long

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public CurrencyCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=7), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BudgetPeriod As System.Nullable(Of Integer)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=8), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public OrderNumber As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=9)> _
    Public PaymentService As PaymentServiceType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=10), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public Card As BankCard

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=11), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BankAccount As System.Nullable(Of BankAccountType)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=12), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public FirstName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=13), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public LastName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=14), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BillingAddress As Address

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=15), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ShippingAddress As Address

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=16), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public Email As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=17), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public MobilePhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=18), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public HomePhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=19), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public WorkPhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=20), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public PAResPayload As String

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New( _
                ByVal MessageHeader As MessageHeader, _
                ByVal MerchantID As String, _
                ByVal TransactionID As String, _
                ByVal PreviousTransactionID As String, _
                ByVal TransactionDateTime As System.Nullable(Of Date), _
                ByVal ReconID As String, _
                ByVal Amount As Long, _
                ByVal CurrencyCode As String, _
                ByVal BudgetPeriod As System.Nullable(Of Integer), _
                ByVal OrderNumber As String, _
                ByVal PaymentService As PaymentServiceType, _
                ByVal Card As BankCard, _
                ByVal BankAccount As System.Nullable(Of BankAccountType), _
                ByVal FirstName As String, _
                ByVal LastName As String, _
                ByVal BillingAddress As Address, _
                ByVal ShippingAddress As Address, _
                ByVal Email As String, _
                ByVal MobilePhone As String, _
                ByVal HomePhone As String, _
                ByVal WorkPhone As String, _
                ByVal PAResPayload As String)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.MerchantID = MerchantID
        Me.TransactionID = TransactionID
        Me.PreviousTransactionID = PreviousTransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.Amount = Amount
        Me.CurrencyCode = CurrencyCode
        Me.BudgetPeriod = BudgetPeriod
        Me.OrderNumber = OrderNumber
        Me.PaymentService = PaymentService
        Me.Card = Card
        Me.BankAccount = BankAccount
        Me.FirstName = FirstName
        Me.LastName = LastName
        Me.BillingAddress = BillingAddress
        Me.ShippingAddress = ShippingAddress
        Me.Email = Email
        Me.MobilePhone = MobilePhone
        Me.HomePhone = HomePhone
        Me.WorkPhone = WorkPhone
        Me.PAResPayload = PAResPayload
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="AuthorizeResponse", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class AuthorizeResponse

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public AuthCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4)> _
    Public TransactionStatus As TransactionStatusType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public ResponseDetail As ResponseDetail

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public AuthAmount As System.Nullable(Of Long)

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal TransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal AuthCode As String, ByVal TransactionStatus As TransactionStatusType, ByVal ResponseDetail As ResponseDetail, ByVal AuthAmount As System.Nullable(Of Long))
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.TransactionID = TransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.AuthCode = AuthCode
        Me.TransactionStatus = TransactionStatus
        Me.ResponseDetail = ResponseDetail
        Me.AuthAmount = AuthAmount
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="CaptureRequest", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class CaptureRequest

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public MerchantID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2)> _
    Public PreviousTransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public Amount As Long

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public CurrencyCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=7), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public OrderNumber As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=8)> _
    Public PaymentService As PaymentServiceType

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal MerchantID As String, ByVal TransactionID As String, ByVal PreviousTransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal Amount As Long, ByVal CurrencyCode As String, ByVal OrderNumber As String, ByVal PaymentService As PaymentServiceType)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.MerchantID = MerchantID
        Me.TransactionID = TransactionID
        Me.PreviousTransactionID = PreviousTransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.Amount = Amount
        Me.CurrencyCode = CurrencyCode
        Me.OrderNumber = OrderNumber
        Me.PaymentService = PaymentService
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="CaptureResponse", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class CaptureResponse

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public AuthCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4)> _
    Public TransactionStatus As TransactionStatusType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public ResponseDetail As ResponseDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal TransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal AuthCode As String, ByVal TransactionStatus As TransactionStatusType, ByVal ResponseDetail As ResponseDetail)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.TransactionID = TransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.AuthCode = AuthCode
        Me.TransactionStatus = TransactionStatus
        Me.ResponseDetail = ResponseDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="PaymentRequest", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class PaymentRequest

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public MerchantID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2)> _
    Public PreviousTransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public Amount As Long

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public CurrencyCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=7), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BudgetPeriod As System.Nullable(Of Integer)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=8), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public OrderNumber As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=9)> _
    Public PaymentService As PaymentServiceType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=10), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public Card As BankCard

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=11), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BankAccount As System.Nullable(Of BankAccountType)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=12), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public FirstName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=13), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public LastName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=14), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BillingAddress As Address

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=15), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ShippingAddress As Address

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=16), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public Email As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=17), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public MobilePhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=18), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public HomePhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=19), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public WorkPhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=20), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public PAResPayload As String

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New( _
                ByVal MessageHeader As MessageHeader, _
                ByVal MerchantID As String, _
                ByVal TransactionID As String, _
                ByVal PreviousTransactionID As String, _
                ByVal TransactionDateTime As System.Nullable(Of Date), _
                ByVal ReconID As String, _
                ByVal Amount As Long, _
                ByVal CurrencyCode As String, _
                ByVal BudgetPeriod As System.Nullable(Of Integer), _
                ByVal OrderNumber As String, _
                ByVal PaymentService As PaymentServiceType, _
                ByVal Card As BankCard, _
                ByVal BankAccount As System.Nullable(Of BankAccountType), _
                ByVal FirstName As String, _
                ByVal LastName As String, _
                ByVal BillingAddress As Address, _
                ByVal ShippingAddress As Address, _
                ByVal Email As String, _
                ByVal MobilePhone As String, _
                ByVal HomePhone As String, _
                ByVal WorkPhone As String, _
                ByVal PAResPayload As String)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.MerchantID = MerchantID
        Me.TransactionID = TransactionID
        Me.PreviousTransactionID = PreviousTransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.Amount = Amount
        Me.CurrencyCode = CurrencyCode
        Me.BudgetPeriod = BudgetPeriod
        Me.OrderNumber = OrderNumber
        Me.PaymentService = PaymentService
        Me.Card = Card
        Me.BankAccount = BankAccount
        Me.FirstName = FirstName
        Me.LastName = LastName
        Me.BillingAddress = BillingAddress
        Me.ShippingAddress = ShippingAddress
        Me.Email = Email
        Me.MobilePhone = MobilePhone
        Me.HomePhone = HomePhone
        Me.WorkPhone = WorkPhone
        Me.PAResPayload = PAResPayload
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="PaymentResponse", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class PaymentResponse

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public AuthCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4)> _
    Public TransactionStatus As TransactionStatusType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public ResponseDetail As ResponseDetail

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public AuthAmount As System.Nullable(Of Long)

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal TransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal AuthCode As String, ByVal TransactionStatus As TransactionStatusType, ByVal ResponseDetail As ResponseDetail, ByVal AuthAmount As System.Nullable(Of Long))
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.TransactionID = TransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.AuthCode = AuthCode
        Me.TransactionStatus = TransactionStatus
        Me.ResponseDetail = ResponseDetail
        Me.AuthAmount = AuthAmount
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RefundRequest", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class RefundRequest

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public MerchantID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2)> _
    Public PreviousTransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public Amount As Long

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public CurrencyCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=7), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public OrderNumber As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=8)> _
    Public PaymentService As PaymentServiceType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=9), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public Card As BankCard

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=10), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BankAccount As System.Nullable(Of BankAccountType)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=11), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public FirstName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=12), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public LastName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=13), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public BillingAddress As Address

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=14), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ShippingAddress As Address

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=15), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public Email As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=16), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public MobilePhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=17), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public HomePhone As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=18), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public WorkPhone As String

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New( _
                ByVal MessageHeader As MessageHeader, _
                ByVal MerchantID As String, _
                ByVal TransactionID As String, _
                ByVal PreviousTransactionID As String, _
                ByVal TransactionDateTime As System.Nullable(Of Date), _
                ByVal ReconID As String, _
                ByVal Amount As Long, _
                ByVal CurrencyCode As String, _
                ByVal OrderNumber As String, _
                ByVal PaymentService As PaymentServiceType, _
                ByVal Card As BankCard, _
                ByVal BankAccount As System.Nullable(Of BankAccountType), _
                ByVal FirstName As String, _
                ByVal LastName As String, _
                ByVal BillingAddress As Address, _
                ByVal ShippingAddress As Address, _
                ByVal Email As String, _
                ByVal MobilePhone As String, _
                ByVal HomePhone As String, _
                ByVal WorkPhone As String)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.MerchantID = MerchantID
        Me.TransactionID = TransactionID
        Me.PreviousTransactionID = PreviousTransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.Amount = Amount
        Me.CurrencyCode = CurrencyCode
        Me.OrderNumber = OrderNumber
        Me.PaymentService = PaymentService
        Me.Card = Card
        Me.BankAccount = BankAccount
        Me.FirstName = FirstName
        Me.LastName = LastName
        Me.BillingAddress = BillingAddress
        Me.ShippingAddress = ShippingAddress
        Me.Email = Email
        Me.MobilePhone = MobilePhone
        Me.HomePhone = HomePhone
        Me.WorkPhone = WorkPhone
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RefundResponse", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class RefundResponse

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public AuthCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4)> _
    Public TransactionStatus As TransactionStatusType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public ResponseDetail As ResponseDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal TransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal AuthCode As String, ByVal TransactionStatus As TransactionStatusType, ByVal ResponseDetail As ResponseDetail)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.TransactionID = TransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.AuthCode = AuthCode
        Me.TransactionStatus = TransactionStatus
        Me.ResponseDetail = ResponseDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="VoidRequest", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class VoidRequest

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public MerchantID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2)> _
    Public PreviousTransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public OrderNumber As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6)> _
    Public PaymentService As PaymentServiceType

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal MerchantID As String, ByVal TransactionID As String, ByVal PreviousTransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal OrderNumber As String, ByVal PaymentService As PaymentServiceType)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.MerchantID = MerchantID
        Me.TransactionID = TransactionID
        Me.PreviousTransactionID = PreviousTransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.OrderNumber = OrderNumber
        Me.PaymentService = PaymentService
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="VoidResponse", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class VoidResponse

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3)> _
    Public TransactionStatus As TransactionStatusType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4)> _
    Public ResponseDetail As ResponseDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal TransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal TransactionStatus As TransactionStatusType, ByVal ResponseDetail As ResponseDetail)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.TransactionID = TransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.TransactionStatus = TransactionStatus
        Me.ResponseDetail = ResponseDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Secure3DLookupRequest", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class Secure3DLookupRequest

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public MerchantID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4)> _
    Public Amount As Long

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public CurrencyCode As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public OrderNumber As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=7), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public Card As BankCard

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal MerchantID As String, ByVal TransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal Amount As Long, ByVal CurrencyCode As String, ByVal OrderNumber As String, ByVal Card As BankCard)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.MerchantID = MerchantID
        Me.TransactionID = TransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.Amount = Amount
        Me.CurrencyCode = CurrencyCode
        Me.OrderNumber = OrderNumber
        Me.Card = Card
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Secure3DLookupResponse", WrapperNamespace:="http://www.ecentricswitch.co.za/paymentgateway/v1", IsWrapped:=True)> _
Partial Public Class Secure3DLookupResponse

    <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1")> _
    Public MessageHeader As MessageHeader

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=0)> _
    Public TransactionID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=1), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public TransactionDateTime As System.Nullable(Of Date)

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=2), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public ReconID As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=3)> _
    Public TransactionStatus As TransactionStatusType

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=4)> _
    Public ResponseDetail As ResponseDetail

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=5)> _
    Public Enrolled As Boolean

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=6), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public AcsUrl As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.ecentricswitch.co.za/paymentgateway/v1", Order:=7), _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public PAReqPayload As String

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal MessageHeader As MessageHeader, ByVal TransactionID As String, ByVal TransactionDateTime As System.Nullable(Of Date), ByVal ReconID As String, ByVal TransactionStatus As TransactionStatusType, ByVal ResponseDetail As ResponseDetail, ByVal Enrolled As Boolean, ByVal AcsUrl As String, ByVal PAReqPayload As String)
        MyBase.New()
        Me.MessageHeader = MessageHeader
        Me.TransactionID = TransactionID
        Me.TransactionDateTime = TransactionDateTime
        Me.ReconID = ReconID
        Me.TransactionStatus = TransactionStatus
        Me.ResponseDetail = ResponseDetail
        Me.Enrolled = Enrolled
        Me.AcsUrl = AcsUrl
        Me.PAReqPayload = PAReqPayload
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Public Interface IPaymentGatewayServiceChannel
    Inherits IPaymentGatewayService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Partial Public Class PaymentGatewayServiceClient
    Inherits System.ServiceModel.ClientBase(Of IPaymentGatewayService)
    Implements IPaymentGatewayService

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function IPaymentGatewayService_Authorize(ByVal request As AuthorizeRequest) As AuthorizeResponse Implements IPaymentGatewayService.Authorize
        Return MyBase.Channel.Authorize(request)
    End Function

    Public Function Authorize( _
                ByRef MessageHeader As MessageHeader, _
                ByVal MerchantID As String, _
                ByRef TransactionID As String, _
                ByVal PreviousTransactionID As String, _
                ByRef TransactionDateTime As System.Nullable(Of Date), _
                ByRef ReconID As String, _
                ByVal Amount As Long, _
                ByVal CurrencyCode As String, _
                ByVal BudgetPeriod As System.Nullable(Of Integer), _
                ByVal OrderNumber As String, _
                ByVal PaymentService As PaymentServiceType, _
                ByVal Card As BankCard, _
                ByVal BankAccount As System.Nullable(Of BankAccountType), _
                ByVal FirstName As String, _
                ByVal LastName As String, _
                ByVal BillingAddress As Address, _
                ByVal ShippingAddress As Address, _
                ByVal Email As String, _
                ByVal MobilePhone As String, _
                ByVal HomePhone As String, _
                ByVal WorkPhone As String, _
                ByVal PAResPayload As String, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef TransactionStatus As TransactionStatusType, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef ResponseDetail As ResponseDetail, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef AuthAmount As System.Nullable(Of Long)) As String
        Dim inValue As AuthorizeRequest = New AuthorizeRequest
        inValue.MessageHeader = MessageHeader
        inValue.MerchantID = MerchantID
        inValue.TransactionID = TransactionID
        inValue.PreviousTransactionID = PreviousTransactionID
        inValue.TransactionDateTime = TransactionDateTime
        inValue.ReconID = ReconID
        inValue.Amount = Amount
        inValue.CurrencyCode = CurrencyCode
        inValue.BudgetPeriod = BudgetPeriod
        inValue.OrderNumber = OrderNumber
        inValue.PaymentService = PaymentService
        inValue.Card = Card
        inValue.BankAccount = BankAccount
        inValue.FirstName = FirstName
        inValue.LastName = LastName
        inValue.BillingAddress = BillingAddress
        inValue.ShippingAddress = ShippingAddress
        inValue.Email = Email
        inValue.MobilePhone = MobilePhone
        inValue.HomePhone = HomePhone
        inValue.WorkPhone = WorkPhone
        inValue.PAResPayload = PAResPayload
        Dim retVal As AuthorizeResponse = CType(Me, IPaymentGatewayService).Authorize(inValue)
        MessageHeader = retVal.MessageHeader
        TransactionID = retVal.TransactionID
        TransactionDateTime = retVal.TransactionDateTime
        ReconID = retVal.ReconID
        TransactionStatus = retVal.TransactionStatus
        ResponseDetail = retVal.ResponseDetail
        AuthAmount = retVal.AuthAmount
        Return retVal.AuthCode
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function IPaymentGatewayService_Capture(ByVal request As CaptureRequest) As CaptureResponse Implements IPaymentGatewayService.Capture
        Return MyBase.Channel.Capture(request)
    End Function

    Public Function Capture(ByRef MessageHeader As MessageHeader, ByVal MerchantID As String, ByRef TransactionID As String, ByVal PreviousTransactionID As String, ByRef TransactionDateTime As System.Nullable(Of Date), ByRef ReconID As String, ByVal Amount As Long, ByVal CurrencyCode As String, ByVal OrderNumber As String, ByVal PaymentService As PaymentServiceType, <System.Runtime.InteropServices.OutAttribute()> ByRef TransactionStatus As TransactionStatusType, <System.Runtime.InteropServices.OutAttribute()> ByRef ResponseDetail As ResponseDetail) As String
        Dim inValue As CaptureRequest = New CaptureRequest
        inValue.MessageHeader = MessageHeader
        inValue.MerchantID = MerchantID
        inValue.TransactionID = TransactionID
        inValue.PreviousTransactionID = PreviousTransactionID
        inValue.TransactionDateTime = TransactionDateTime
        inValue.ReconID = ReconID
        inValue.Amount = Amount
        inValue.CurrencyCode = CurrencyCode
        inValue.OrderNumber = OrderNumber
        inValue.PaymentService = PaymentService
        Dim retVal As CaptureResponse = CType(Me, IPaymentGatewayService).Capture(inValue)
        MessageHeader = retVal.MessageHeader
        TransactionID = retVal.TransactionID
        TransactionDateTime = retVal.TransactionDateTime
        ReconID = retVal.ReconID
        TransactionStatus = retVal.TransactionStatus
        ResponseDetail = retVal.ResponseDetail
        Return retVal.AuthCode
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function IPaymentGatewayService_Payment(ByVal request As PaymentRequest) As PaymentResponse Implements IPaymentGatewayService.Payment
        Return MyBase.Channel.Payment(request)
    End Function

    Public Function Payment( _
                ByRef MessageHeader As MessageHeader, _
                ByVal MerchantID As String, _
                ByRef TransactionID As String, _
                ByVal PreviousTransactionID As String, _
                ByRef TransactionDateTime As System.Nullable(Of Date), _
                ByRef ReconID As String, _
                ByVal Amount As Long, _
                ByVal CurrencyCode As String, _
                ByVal BudgetPeriod As System.Nullable(Of Integer), _
                ByVal OrderNumber As String, _
                ByVal PaymentService As PaymentServiceType, _
                ByVal Card As BankCard, _
                ByVal BankAccount As System.Nullable(Of BankAccountType), _
                ByVal FirstName As String, _
                ByVal LastName As String, _
                ByVal BillingAddress As Address, _
                ByVal ShippingAddress As Address, _
                ByVal Email As String, _
                ByVal MobilePhone As String, _
                ByVal HomePhone As String, _
                ByVal WorkPhone As String, _
                ByVal PAResPayload As String, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef TransactionStatus As TransactionStatusType, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef ResponseDetail As ResponseDetail, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef AuthAmount As System.Nullable(Of Long)) As String
        Dim inValue As PaymentRequest = New PaymentRequest
        inValue.MessageHeader = MessageHeader
        inValue.MerchantID = MerchantID
        inValue.TransactionID = TransactionID
        inValue.PreviousTransactionID = PreviousTransactionID
        inValue.TransactionDateTime = TransactionDateTime
        inValue.ReconID = ReconID
        inValue.Amount = Amount
        inValue.CurrencyCode = CurrencyCode
        inValue.BudgetPeriod = BudgetPeriod
        inValue.OrderNumber = OrderNumber
        inValue.PaymentService = PaymentService
        inValue.Card = Card
        inValue.BankAccount = BankAccount
        inValue.FirstName = FirstName
        inValue.LastName = LastName
        inValue.BillingAddress = BillingAddress
        inValue.ShippingAddress = ShippingAddress
        inValue.Email = Email
        inValue.MobilePhone = MobilePhone
        inValue.HomePhone = HomePhone
        inValue.WorkPhone = WorkPhone
        inValue.PAResPayload = PAResPayload
        Dim retVal As PaymentResponse = CType(Me, IPaymentGatewayService).Payment(inValue)
        MessageHeader = retVal.MessageHeader
        TransactionID = retVal.TransactionID
        TransactionDateTime = retVal.TransactionDateTime
        ReconID = retVal.ReconID
        TransactionStatus = retVal.TransactionStatus
        ResponseDetail = retVal.ResponseDetail
        AuthAmount = retVal.AuthAmount
        Return retVal.AuthCode
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function IPaymentGatewayService_Refund(ByVal request As RefundRequest) As RefundResponse Implements IPaymentGatewayService.Refund
        Return MyBase.Channel.Refund(request)
    End Function

    Public Function Refund( _
                ByRef MessageHeader As MessageHeader, _
                ByVal MerchantID As String, _
                ByRef TransactionID As String, _
                ByVal PreviousTransactionID As String, _
                ByRef TransactionDateTime As System.Nullable(Of Date), _
                ByRef ReconID As String, _
                ByVal Amount As Long, _
                ByVal CurrencyCode As String, _
                ByVal OrderNumber As String, _
                ByVal PaymentService As PaymentServiceType, _
                ByVal Card As BankCard, _
                ByVal BankAccount As System.Nullable(Of BankAccountType), _
                ByVal FirstName As String, _
                ByVal LastName As String, _
                ByVal BillingAddress As Address, _
                ByVal ShippingAddress As Address, _
                ByVal Email As String, _
                ByVal MobilePhone As String, _
                ByVal HomePhone As String, _
                ByVal WorkPhone As String, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef TransactionStatus As TransactionStatusType, _
                <System.Runtime.InteropServices.OutAttribute()> ByRef ResponseDetail As ResponseDetail) As String
        Dim inValue As RefundRequest = New RefundRequest
        inValue.MessageHeader = MessageHeader
        inValue.MerchantID = MerchantID
        inValue.TransactionID = TransactionID
        inValue.PreviousTransactionID = PreviousTransactionID
        inValue.TransactionDateTime = TransactionDateTime
        inValue.ReconID = ReconID
        inValue.Amount = Amount
        inValue.CurrencyCode = CurrencyCode
        inValue.OrderNumber = OrderNumber
        inValue.PaymentService = PaymentService
        inValue.Card = Card
        inValue.BankAccount = BankAccount
        inValue.FirstName = FirstName
        inValue.LastName = LastName
        inValue.BillingAddress = BillingAddress
        inValue.ShippingAddress = ShippingAddress
        inValue.Email = Email
        inValue.MobilePhone = MobilePhone
        inValue.HomePhone = HomePhone
        inValue.WorkPhone = WorkPhone
        Dim retVal As RefundResponse = CType(Me, IPaymentGatewayService).Refund(inValue)
        MessageHeader = retVal.MessageHeader
        TransactionID = retVal.TransactionID
        TransactionDateTime = retVal.TransactionDateTime
        ReconID = retVal.ReconID
        TransactionStatus = retVal.TransactionStatus
        ResponseDetail = retVal.ResponseDetail
        Return retVal.AuthCode
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function IPaymentGatewayService_Void(ByVal request As VoidRequest) As VoidResponse Implements IPaymentGatewayService.Void
        Return MyBase.Channel.Void(request)
    End Function

    Public Function Void(ByRef MessageHeader As MessageHeader, ByVal MerchantID As String, ByRef TransactionID As String, ByVal PreviousTransactionID As String, ByRef TransactionDateTime As System.Nullable(Of Date), ByRef ReconID As String, ByVal OrderNumber As String, ByVal PaymentService As PaymentServiceType, <System.Runtime.InteropServices.OutAttribute()> ByRef ResponseDetail As ResponseDetail) As TransactionStatusType
        Dim inValue As VoidRequest = New VoidRequest
        inValue.MessageHeader = MessageHeader
        inValue.MerchantID = MerchantID
        inValue.TransactionID = TransactionID
        inValue.PreviousTransactionID = PreviousTransactionID
        inValue.TransactionDateTime = TransactionDateTime
        inValue.ReconID = ReconID
        inValue.OrderNumber = OrderNumber
        inValue.PaymentService = PaymentService
        Dim retVal As VoidResponse = CType(Me, IPaymentGatewayService).Void(inValue)
        MessageHeader = retVal.MessageHeader
        TransactionID = retVal.TransactionID
        TransactionDateTime = retVal.TransactionDateTime
        ReconID = retVal.ReconID
        ResponseDetail = retVal.ResponseDetail
        Return retVal.TransactionStatus
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function IPaymentGatewayService_Secure3DLookup(ByVal request As Secure3DLookupRequest) As Secure3DLookupResponse Implements IPaymentGatewayService.Secure3DLookup
        Return MyBase.Channel.Secure3DLookup(request)
    End Function

    Public Function Secure3DLookup(ByRef MessageHeader As MessageHeader, ByVal MerchantID As String, ByRef TransactionID As String, ByRef TransactionDateTime As System.Nullable(Of Date), ByRef ReconID As String, ByVal Amount As Long, ByVal CurrencyCode As String, ByVal OrderNumber As String, ByVal Card As BankCard, <System.Runtime.InteropServices.OutAttribute()> ByRef ResponseDetail As ResponseDetail, <System.Runtime.InteropServices.OutAttribute()> ByRef Enrolled As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef AcsUrl As String, <System.Runtime.InteropServices.OutAttribute()> ByRef PAReqPayload As String) As TransactionStatusType
        Dim inValue As Secure3DLookupRequest = New Secure3DLookupRequest
        inValue.MessageHeader = MessageHeader
        inValue.MerchantID = MerchantID
        inValue.TransactionID = TransactionID
        inValue.TransactionDateTime = TransactionDateTime
        inValue.ReconID = ReconID
        inValue.Amount = Amount
        inValue.CurrencyCode = CurrencyCode
        inValue.OrderNumber = OrderNumber
        inValue.Card = Card
        Dim retVal As Secure3DLookupResponse = CType(Me, IPaymentGatewayService).Secure3DLookup(inValue)
        MessageHeader = retVal.MessageHeader
        TransactionID = retVal.TransactionID
        TransactionDateTime = retVal.TransactionDateTime
        ReconID = retVal.ReconID
        ResponseDetail = retVal.ResponseDetail
        Enrolled = retVal.Enrolled
        AcsUrl = retVal.AcsUrl
        PAReqPayload = retVal.PAReqPayload
        Return retVal.TransactionStatus
    End Function
End Class
