<%@ Page Language="VB" AutoEventWireup="false" MasterPageFile="~/MasterPages/MasterPage.master" CodeFile="ModuleAdmin.aspx.vb" Inherits="Modules_ModuleAdmin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Content1" runat="Server">
    <div id="pageMaintenanceTopNavigation">
        <ul>
            <li><a href="../Default.aspx"><asp:Literal ID="ltlHomeLink" runat="server" /></a></li>
        </ul>
    </div>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="Content2" runat="Server">
    <div id="moduleAdmin">
        <asp:GridView ID="ModulesView" CssClass="defaultTable" runat="server" AllowSorting="True" AutoGenerateDeleteButton="True"
            DataKeyNames="SUPPLYNET_MODULE_ID" AllowPaging="True" PagerSettings-FirstPageText="First"
            PagerSettings-LastPageText="Last" PagerSettings-NextPageText="Next" PagerSettings-PreviousPageText="Previous"
            PageSize="20" PagerSettings-Mode="NumericFirstLast">
            <Columns>
                <asp:HyperLinkField DataNavigateUrlFields="SUPPLYNET_MODULE_ID,BUSINESS_UNIT" DataNavigateUrlFormatString="~/Modules/ModuleDetails.aspx?ID={0}&BU={1}"
                    Text="Edit" />
                <%--<asp:HyperLinkField DataNavigateUrlFields="SUPPLYNET_MODULE_ID" DataNavigateUrlFormatString="~/Users/UsersAdmin.aspx?PartnerID={0}"
                    Text="Users" />--%>
            </Columns>
        </asp:GridView>
        <div class="moduleAdminBtn">
            <asp:Button CssClass="button" ID="btnAdd" runat="server" Text="Add Module" />
        </div>
    </div>
</asp:Content>