'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace BEKOSAPStockCheck

    '
    'This source code was auto-generated by wsdl, Version=2.0.50727.42.
    '

    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    'CODEGEN: The optional WSDL extension element 'EndpointReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/08/addressing' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZW61V", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> _
    Partial Public Class ZW61V
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private BAPI_MATERIAL_AVAILABILITYOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "http://195.87.244.139:8000/sap/bc/srt/wsdl/sdef_ZW61V/wsdl11/ws_policy/document?s" & _
                "ap-client=046"
        End Sub

        '''<remarks/>
        Public Event BAPI_MATERIAL_AVAILABILITYCompleted As BAPI_MATERIAL_AVAILABILITYCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)> _
        Public Function BAPI_MATERIAL_AVAILABILITY(<System.Xml.Serialization.XmlElementAttribute("BAPI_MATERIAL_AVAILABILITY", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal BAPI_MATERIAL_AVAILABILITY1 As BAPI_MATERIAL_AVAILABILITY) As <System.Xml.Serialization.XmlElementAttribute("BAPI_MATERIAL_AVAILABILITYResponse", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> BAPI_MATERIAL_AVAILABILITYResponse
            Dim results() As Object = Me.Invoke("BAPI_MATERIAL_AVAILABILITY", New Object() {BAPI_MATERIAL_AVAILABILITY1})
            Return CType(results(0), BAPI_MATERIAL_AVAILABILITYResponse)
        End Function

        '''<remarks/>
        Public Function BeginBAPI_MATERIAL_AVAILABILITY(ByVal BAPI_MATERIAL_AVAILABILITY1 As BAPI_MATERIAL_AVAILABILITY, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("BAPI_MATERIAL_AVAILABILITY", New Object() {BAPI_MATERIAL_AVAILABILITY1}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndBAPI_MATERIAL_AVAILABILITY(ByVal asyncResult As System.IAsyncResult) As BAPI_MATERIAL_AVAILABILITYResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), BAPI_MATERIAL_AVAILABILITYResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub BAPI_MATERIAL_AVAILABILITYAsync(ByVal BAPI_MATERIAL_AVAILABILITY1 As BAPI_MATERIAL_AVAILABILITY)
            Me.BAPI_MATERIAL_AVAILABILITYAsync(BAPI_MATERIAL_AVAILABILITY1, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub BAPI_MATERIAL_AVAILABILITYAsync(ByVal BAPI_MATERIAL_AVAILABILITY1 As BAPI_MATERIAL_AVAILABILITY, ByVal userState As Object)
            If (Me.BAPI_MATERIAL_AVAILABILITYOperationCompleted Is Nothing) Then
                Me.BAPI_MATERIAL_AVAILABILITYOperationCompleted = AddressOf Me.OnBAPI_MATERIAL_AVAILABILITYOperationCompleted
            End If
            Me.InvokeAsync("BAPI_MATERIAL_AVAILABILITY", New Object() {BAPI_MATERIAL_AVAILABILITY1}, Me.BAPI_MATERIAL_AVAILABILITYOperationCompleted, userState)
        End Sub

        Private Sub OnBAPI_MATERIAL_AVAILABILITYOperationCompleted(ByVal arg As Object)
            If (Not (Me.BAPI_MATERIAL_AVAILABILITYCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BAPI_MATERIAL_AVAILABILITYCompleted(Me, New BAPI_MATERIAL_AVAILABILITYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:sap-com:document:sap:rfc:functions")> _
    Partial Public Class BAPI_MATERIAL_AVAILABILITY

        Private bATCHField As String

        Private cHECK_RULEField As String

        Private cUSTOMERField As String

        Private dEC_FOR_ROUNDINGField As Short

        Private dEC_FOR_ROUNDINGFieldSpecified As Boolean

        Private dEC_FOR_ROUNDING_XField As String

        Private dOC_NUMBERField As String

        Private iTM_NUMBERField As String

        Private mATERIALField As String

        Private mATERIAL_EVGField As BAPIMGVMATNR

        Private pLANTField As String

        Private rEAD_ATP_LOCKField As String

        Private rEAD_ATP_LOCK_XField As String

        Private sTGE_LOCField As String

        Private sTOCK_INDField As String

        Private uNITField As String

        Private wBS_ELEMField As String

        Private wMDVEXField() As BAPIWMDVE

        Private wMDVSXField() As BAPIWMDVS

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property BATCH() As String
            Get
                Return Me.bATCHField
            End Get
            Set(ByVal value As String)
                Me.bATCHField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property CHECK_RULE() As String
            Get
                Return Me.cHECK_RULEField
            End Get
            Set(ByVal value As String)
                Me.cHECK_RULEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property CUSTOMER() As String
            Get
                Return Me.cUSTOMERField
            End Get
            Set(ByVal value As String)
                Me.cUSTOMERField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property DEC_FOR_ROUNDING() As Short
            Get
                Return Me.dEC_FOR_ROUNDINGField
            End Get
            Set(ByVal value As Short)
                Me.dEC_FOR_ROUNDINGField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DEC_FOR_ROUNDINGSpecified() As Boolean
            Get
                Return Me.dEC_FOR_ROUNDINGFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dEC_FOR_ROUNDINGFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property DEC_FOR_ROUNDING_X() As String
            Get
                Return Me.dEC_FOR_ROUNDING_XField
            End Get
            Set(ByVal value As String)
                Me.dEC_FOR_ROUNDING_XField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property DOC_NUMBER() As String
            Get
                Return Me.dOC_NUMBERField
            End Get
            Set(ByVal value As String)
                Me.dOC_NUMBERField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property ITM_NUMBER() As String
            Get
                Return Me.iTM_NUMBERField
            End Get
            Set(ByVal value As String)
                Me.iTM_NUMBERField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MATERIAL() As String
            Get
                Return Me.mATERIALField
            End Get
            Set(ByVal value As String)
                Me.mATERIALField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MATERIAL_EVG() As BAPIMGVMATNR
            Get
                Return Me.mATERIAL_EVGField
            End Get
            Set(ByVal value As BAPIMGVMATNR)
                Me.mATERIAL_EVGField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property PLANT() As String
            Get
                Return Me.pLANTField
            End Get
            Set(ByVal value As String)
                Me.pLANTField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property READ_ATP_LOCK() As String
            Get
                Return Me.rEAD_ATP_LOCKField
            End Get
            Set(ByVal value As String)
                Me.rEAD_ATP_LOCKField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property READ_ATP_LOCK_X() As String
            Get
                Return Me.rEAD_ATP_LOCK_XField
            End Get
            Set(ByVal value As String)
                Me.rEAD_ATP_LOCK_XField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property STGE_LOC() As String
            Get
                Return Me.sTGE_LOCField
            End Get
            Set(ByVal value As String)
                Me.sTGE_LOCField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property STOCK_IND() As String
            Get
                Return Me.sTOCK_INDField
            End Get
            Set(ByVal value As String)
                Me.sTOCK_INDField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property UNIT() As String
            Get
                Return Me.uNITField
            End Get
            Set(ByVal value As String)
                Me.uNITField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property WBS_ELEM() As String
            Get
                Return Me.wBS_ELEMField
            End Get
            Set(ByVal value As String)
                Me.wBS_ELEMField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)> _
        Public Property WMDVEX() As BAPIWMDVE()
            Get
                Return Me.wMDVEXField
            End Get
            Set(ByVal value As BAPIWMDVE())
                Me.wMDVEXField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)> _
        Public Property WMDVSX() As BAPIWMDVS()
            Get
                Return Me.wMDVSXField
            End Get
            Set(ByVal value As BAPIWMDVS())
                Me.wMDVSXField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")> _
    Partial Public Class BAPIMGVMATNR

        Private mATERIAL_EXTField As String

        Private mATERIAL_VERSField As String

        Private mATERIAL_GUIDField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MATERIAL_EXT() As String
            Get
                Return Me.mATERIAL_EXTField
            End Get
            Set(ByVal value As String)
                Me.mATERIAL_EXTField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MATERIAL_VERS() As String
            Get
                Return Me.mATERIAL_VERSField
            End Get
            Set(ByVal value As String)
                Me.mATERIAL_VERSField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MATERIAL_GUID() As String
            Get
                Return Me.mATERIAL_GUIDField
            End Get
            Set(ByVal value As String)
                Me.mATERIAL_GUIDField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")> _
    Partial Public Class BAPIRETURN

        Private tYPEField As String

        Private cODEField As String

        Private mESSAGEField As String

        Private lOG_NOField As String

        Private lOG_MSG_NOField As String

        Private mESSAGE_V1Field As String

        Private mESSAGE_V2Field As String

        Private mESSAGE_V3Field As String

        Private mESSAGE_V4Field As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property TYPE() As String
            Get
                Return Me.tYPEField
            End Get
            Set(ByVal value As String)
                Me.tYPEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property CODE() As String
            Get
                Return Me.cODEField
            End Get
            Set(ByVal value As String)
                Me.cODEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE() As String
            Get
                Return Me.mESSAGEField
            End Get
            Set(ByVal value As String)
                Me.mESSAGEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LOG_NO() As String
            Get
                Return Me.lOG_NOField
            End Get
            Set(ByVal value As String)
                Me.lOG_NOField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LOG_MSG_NO() As String
            Get
                Return Me.lOG_MSG_NOField
            End Get
            Set(ByVal value As String)
                Me.lOG_MSG_NOField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V1() As String
            Get
                Return Me.mESSAGE_V1Field
            End Get
            Set(ByVal value As String)
                Me.mESSAGE_V1Field = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V2() As String
            Get
                Return Me.mESSAGE_V2Field
            End Get
            Set(ByVal value As String)
                Me.mESSAGE_V2Field = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V3() As String
            Get
                Return Me.mESSAGE_V3Field
            End Get
            Set(ByVal value As String)
                Me.mESSAGE_V3Field = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V4() As String
            Get
                Return Me.mESSAGE_V4Field
            End Get
            Set(ByVal value As String)
                Me.mESSAGE_V4Field = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")> _
    Partial Public Class BAPIWMDVS

        Private rEQ_DATEField As String

        Private rEQ_QTYField As Decimal

        Private dELKZField As String

        Private yLINEField As Integer

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property REQ_DATE() As String
            Get
                Return Me.rEQ_DATEField
            End Get
            Set(ByVal value As String)
                Me.rEQ_DATEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property REQ_QTY() As Decimal
            Get
                Return Me.rEQ_QTYField
            End Get
            Set(ByVal value As Decimal)
                Me.rEQ_QTYField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property DELKZ() As String
            Get
                Return Me.dELKZField
            End Get
            Set(ByVal value As String)
                Me.dELKZField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property YLINE() As Integer
            Get
                Return Me.yLINEField
            End Get
            Set(ByVal value As Integer)
                Me.yLINEField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")> _
    Partial Public Class BAPIWMDVE

        Private bDCNTField As String

        Private rEQ_DATEField As String

        Private rEQ_QTYField As Decimal

        Private cOM_DATEField As String

        Private cOM_QTYField As Decimal

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property BDCNT() As String
            Get
                Return Me.bDCNTField
            End Get
            Set(ByVal value As String)
                Me.bDCNTField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property REQ_DATE() As String
            Get
                Return Me.rEQ_DATEField
            End Get
            Set(ByVal value As String)
                Me.rEQ_DATEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property REQ_QTY() As Decimal
            Get
                Return Me.rEQ_QTYField
            End Get
            Set(ByVal value As Decimal)
                Me.rEQ_QTYField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property COM_DATE() As String
            Get
                Return Me.cOM_DATEField
            End Get
            Set(ByVal value As String)
                Me.cOM_DATEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property COM_QTY() As Decimal
            Get
                Return Me.cOM_QTYField
            End Get
            Set(ByVal value As Decimal)
                Me.cOM_QTYField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:sap-com:document:sap:rfc:functions")> _
    Partial Public Class BAPI_MATERIAL_AVAILABILITYResponse

        Private aV_QTY_PLTField As Decimal

        Private dIALOGFLAGField As String

        Private eNDLEADTMEField As String

        Private rETURNField As BAPIRETURN

        Private wMDVEXField() As BAPIWMDVE

        Private wMDVSXField() As BAPIWMDVS

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property AV_QTY_PLT() As Decimal
            Get
                Return Me.aV_QTY_PLTField
            End Get
            Set(ByVal value As Decimal)
                Me.aV_QTY_PLTField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property DIALOGFLAG() As String
            Get
                Return Me.dIALOGFLAGField
            End Get
            Set(ByVal value As String)
                Me.dIALOGFLAGField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property ENDLEADTME() As String
            Get
                Return Me.eNDLEADTMEField
            End Get
            Set(ByVal value As String)
                Me.eNDLEADTMEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property [RETURN]() As BAPIRETURN
            Get
                Return Me.rETURNField
            End Get
            Set(ByVal value As BAPIRETURN)
                Me.rETURNField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)> _
        Public Property WMDVEX() As BAPIWMDVE()
            Get
                Return Me.wMDVEXField
            End Get
            Set(ByVal value As BAPIWMDVE())
                Me.wMDVEXField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)> _
        Public Property WMDVSX() As BAPIWMDVS()
            Get
                Return Me.wMDVSXField
            End Get
            Set(ByVal value As BAPIWMDVS())
                Me.wMDVSXField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub BAPI_MATERIAL_AVAILABILITYCompletedEventHandler(ByVal sender As Object, ByVal e As BAPI_MATERIAL_AVAILABILITYCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class BAPI_MATERIAL_AVAILABILITYCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As BAPI_MATERIAL_AVAILABILITYResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), BAPI_MATERIAL_AVAILABILITYResponse)
            End Get
        End Property
    End Class
End Namespace