<!-- List of countries, enter non-blank VALUE for QuickAddress searching -->

<option value="" selected>Please select...</option>

<option value=""   >Other</option>
<option value="AUS">Australia</option>
<option value="BEL">Belgium</option>
<option value="CAN">Canada</option>
<option value="DNK">Denmark</option>
<option value="FIN">Finland</option>
<option value="FRP">France</option>
<option value="DEU">Germany</option>
<option value="IRL">Ireland</option>
<option value="LUX">Luxembourg</option>
<option value="NLD">Netherlands</option>
<option value="NOR">Norway</option>
<option value="SGF">Singapore</option>
<option value="ESP">Spain</option>
<option value="SWE">Sweden</option>
<option value="GBR">United Kingdom</option>
<option value="GBB">United Kingdom (Businesses)</option>
<option value="GBN">United Kingdom (Names)</option>
<option value="USA">United States</option>
