-- Remove existing index if it exists
IF EXISTS (SELECT * FROM sys.indexes WHERE NAME = 'IDX_BUSI_UNIT_LOGID_PROCESSED' AND OBJECT_ID = OBJECT_ID('tbl_basket_header'))
BEGIN
	DROP INDEX IDX_BUSI_UNIT_LOGID_PROCESSED ON tbl_basket_header
END
GO

-- Add the new index if it doesn't exist already
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE NAME = 'IDX_BUSI_UNIT_LOGID_PROCESSED' AND OBJECT_ID = OBJECT_ID('tbl_basket_header'))
BEGIN
	-- Create the new index
	CREATE NONCLUSTERED INDEX [IDX_BUSI_UNIT_LOGID_PROCESSED] ON [dbo].[tbl_basket_header] 
	(
		[BUSINESS_UNIT] ASC,
		[LOGINID] ASC,
		[PROCESSED] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
END
GO