'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
'******************************************************************
'   CCTransaction.vb
'  
'   Modification Summary
'
'   dd/mm/yy    ID      By      Description
'   --------    -----   ---     -----------
'   03/04/06    /000    Ben     Created. Imported from Orion Dev
'******************************************************************
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=1.1.4322.573.
'
Namespace CardProcessing.Commidea.WebServices

    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="CCTransactionSoap", [Namespace]:="https://www.commidea.webservices.com")> _
    Public Class CCTransaction
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        '<remarks/>
        Public Sub New(ByVal transactionUrl As String)
            MyBase.New()
            '  TEST = "https://testing.commidea.com/CCTransaction.asmx"
            '  LIVE = "https://www.commidea.net/CCTransaction.asmx"
            Me.Url = transactionUrl
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.commidea.webservices.com/CardTxn", RequestNamespace:="https://www.commidea.webservices.com", ResponseNamespace:="https://www.commidea.webservices.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function CardTxn(ByVal xmlStream As String) As <System.Xml.Serialization.XmlElementAttribute("CommideaTxnResponse", IsNullable:=True)> TxnResponse
            Dim results() As Object = Me.Invoke("CardTxn", New Object() {xmlStream})
            Return CType(results(0), TxnResponse)
        End Function

        '<remarks/>
        Public Function BeginCardTxn(ByVal xmlStream As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CardTxn", New Object() {xmlStream}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndCardTxn(ByVal asyncResult As System.IAsyncResult) As TxnResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), TxnResponse)
        End Function
    End Class
End Namespace
