'******************************************************************
'   ConfirmTxn.vb
'  
'   Modification Summary
'
'   dd/mm/yy    ID      By      Description
'   --------    -----   ---     -----------
'   03/04/06    /000    Ben     Created. Imported from Orion Dev
'******************************************************************
'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=1.1.4322.573.
'
Namespace CardProcessing.Commidea.WebServices

    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConfirmTxnSoap", [Namespace]:="https://www.commidea.webservices.com")> _
    Public Class ConfirmTxn
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        '<remarks/>
        Public Sub New(ByVal confirmURL As String)
            MyBase.New()
            ' TEST = "https://testing.commidea.com/ConfirmTxn.asmx"
            ' LIVE = "https://www.commidea.net/ConfirmTxn.asmx"
            Me.Url = confirmURL
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.commidea.webservices.com/ConfirmTransaction", RequestNamespace:="https://www.commidea.webservices.com", ResponseNamespace:="https://www.commidea.webservices.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ConfirmTransaction(ByVal xmlStream As String) As <System.Xml.Serialization.XmlElementAttribute("CommideaTxnResponse", IsNullable:=True)> TxnResponse
            Dim results() As Object = Me.Invoke("ConfirmTransaction", New Object() {xmlStream})
            Return CType(results(0), TxnResponse)
        End Function

        '<remarks/>
        Public Function BeginConfirmTransaction(ByVal xmlStream As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConfirmTransaction", New Object() {xmlStream}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndConfirmTransaction(ByVal asyncResult As System.IAsyncResult) As TxnResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), TxnResponse)
        End Function
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.commidea.webservices.com")> _
    Public Class TxnResponse

        '<remarks/>
        Public StdResponse As StandardResponse

        '<remarks/>
        Public ICCResponse As ICCResponse

        '<remarks/>
        Public FraudResponse As FraudResponse

        '<remarks/>
        Public AuthResponse As AuthResponse

        '<remarks/>
        Public InternalError As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.commidea.webservices.com")> _
    Public Class StandardResponse

        '<remarks/>
        Public Ad1AvsResult As String

        '<remarks/>
        Public CvcResult As String

        '<remarks/>
        Public AuthResult As String

        '<remarks/>
        Public AuthCode As String

        '<remarks/>
        Public VRTel As String

        '<remarks/>
        Public MerchantData As String

        '<remarks/>
        Public AuthMessage As String

        '<remarks/>
        Public TransactionStatus As String

        '<remarks/>
        Public TransactionResult As String

        '<remarks/>
        Public ResultID As String

        '<remarks/>
        Public TransactionID As String

        '<remarks/>
        Public ResultDateTime As String

        '<remarks/>
        Public ResultDateTimestring As String

        '<remarks/>
        Public InvoiceErrorLine As String

        '<remarks/>
        Public InvoiceErrorField As String

        '<remarks/>
        Public ErrorMsg As String

        '<remarks/>
        Public MerchantNumber As String

        '<remarks/>
        Public TID As String

        '<remarks/>
        Public SchemeName As String

        '<remarks/>
        Public FloorLimit As String

        '<remarks/>
        Public EFTSN As String

        '<remarks/>
        Public PcAvsResult As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.commidea.webservices.com")> _
    Public Class AuthResponse

        '<remarks/>
        Public AuxiliaryData As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.commidea.webservices.com")> _
    Public Class FraudResponse

        '<remarks/>
        Public RmResult As String

        '<remarks/>
        Public RmRulecode As String

        '<remarks/>
        Public ScoreFactors As String

        '<remarks/>
        Public ScoreResult As String

        '<remarks/>
        Public Custom1 As String

        '<remarks/>
        Public Custom2 As String

        '<remarks/>
        Public Custom3 As String

        '<remarks/>
        Public Custom4 As String

        '<remarks/>
        Public Custom5 As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.commidea.webservices.com")> _
    Public Class ICCResponse

        '<remarks/>
        Public ARC As String

        '<remarks/>
        Public ARPC As String

        '<remarks/>
        Public IAOD As String

        '<remarks/>
        Public RAD As String

        '<remarks/>
        Public ISD As String
    End Class
End Namespace
