'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.17929.
'
Namespace VanguardWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CommideaGatewaySoap", [Namespace]:="https://www.commidea.webservices.com")>  _
    Partial Public Class CommideaGateway
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ProcessMsgOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://txn-test.cxmlpg.com/XML4/commideagateway.asmx"
        End Sub
        
        '''<remarks/>
        Public Event ProcessMsgCompleted As ProcessMsgCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.commidea.webservices.com/ProcessMsg", RequestNamespace:="https://www.commidea.webservices.com", ResponseNamespace:="https://www.commidea.webservices.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessMsg(ByVal Message As Message) As Message
            Dim results() As Object = Me.Invoke("ProcessMsg", New Object() {Message})
            Return CType(results(0),Message)
        End Function
        
        '''<remarks/>
        Public Function BeginProcessMsg(ByVal Message As Message, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ProcessMsg", New Object() {Message}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndProcessMsg(ByVal asyncResult As System.IAsyncResult) As Message
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Message)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessMsgAsync(ByVal Message As Message)
            Me.ProcessMsgAsync(Message, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessMsgAsync(ByVal Message As Message, ByVal userState As Object)
            If (Me.ProcessMsgOperationCompleted Is Nothing) Then
                Me.ProcessMsgOperationCompleted = AddressOf Me.OnProcessMsgOperationCompleted
            End If
            Me.InvokeAsync("ProcessMsg", New Object() {Message}, Me.ProcessMsgOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessMsgOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessMsgCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessMsgCompleted(Me, New ProcessMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.commidea.webservices.com")>  _
    Partial Public Class Message
        
        Private clientHeaderField As ClientHeader
        
        Private msgTypeField As String
        
        Private msgDataField As String
        
        '''<remarks/>
        Public Property ClientHeader() As ClientHeader
            Get
                Return Me.clientHeaderField
            End Get
            Set
                Me.clientHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MsgType() As String
            Get
                Return Me.msgTypeField
            End Get
            Set
                Me.msgTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MsgData() As String
            Get
                Return Me.msgDataField
            End Get
            Set
                Me.msgDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.commidea.webservices.com")>  _
    Partial Public Class ClientHeader
        
        Private systemIDField As Decimal
        
        Private systemGUIDField As String
        
        Private passcodeField As String
        
        Private processingDBField As String
        
        Private sendAttemptField As Integer
        
        Private cDATAWrappingField As Boolean
        
        Private sourceField As String
        
        '''<remarks/>
        Public Property SystemID() As Decimal
            Get
                Return Me.systemIDField
            End Get
            Set
                Me.systemIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SystemGUID() As String
            Get
                Return Me.systemGUIDField
            End Get
            Set
                Me.systemGUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Passcode() As String
            Get
                Return Me.passcodeField
            End Get
            Set
                Me.passcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProcessingDB() As String
            Get
                Return Me.processingDBField
            End Get
            Set
                Me.processingDBField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SendAttempt() As Integer
            Get
                Return Me.sendAttemptField
            End Get
            Set
                Me.sendAttemptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CDATAWrapping() As Boolean
            Get
                Return Me.cDATAWrappingField
            End Get
            Set
                Me.cDATAWrappingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")>  _
    Public Delegate Sub ProcessMsgCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessMsgCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessMsgCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Message
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Message)
            End Get
        End Property
    End Class
End Namespace
