<%@ Control Language="VB" AutoEventWireup="false" CodeFile="BusinessUnitList.ascx.vb" Inherits="UserControls_BusinessUnitList" %>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TalentEBusinessDBConnectionString %>"
    SelectCommand="SELECT * FROM tbl_bu ORDER BY BUSINESS_UNIT_DESC "></asp:SqlDataSource>
<table>
    <tr>
        <td>
            <div id="Maintenance">
                <asp:GridView ID="grdDataTable" DataKeyNames="BUSINESS_UNIT_ID" DataSourceID="SqlDataSource1"
                    AutoGenerateColumns="False" runat="server" AllowPaging="True" AllowSorting="True"
                    PageSize="20" PagerSettings-Mode="NextPreviousFirstLast" PagerSettings-Position="Bottom"
                    PagerStyle-HorizontalAlign="Right" Caption="<h2>Business Unit Maintenance</h2>" CaptionAlign="Left"
                    SelectedRowStyle-BackColor="#eeeeee" CellPadding="1" CellSpacing="1" HorizontalAlign="Left"
                    AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false">
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField SortExpression="BUSINESS_UNIT_ID" DataField="BUSINESS_UNIT_ID" ReadOnly="True"
                            HeaderText=" ID " />
                        <asp:BoundField SortExpression="BUSINESS_UNIT" DataField="BUSINESS_UNIT" HeaderText=" BUSINESS_UNIT " />
                        <asp:BoundField SortExpression="BUSINESS_UNIT_DESC" DataField="BUSINESS_UNIT_DESC" HeaderText=" Description " />
                    </Columns>
                </asp:GridView>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <br />
            <br />
            <br />
            <div id="BUSINESS_UNIT2" class="BUSINESS_UNIT box2" runat="server">
                <asp:Button ID="cmdEdit" runat="server" Text="Edit" />
                <asp:Button ID="cmdDelete" runat="server" Text="Delete" />
                <asp:Button ID="cmdInsert" runat="server" Text="Insert" />
            </div>
        </td>
    </tr>
</table>
