<%@ Control Language="VB" AutoEventWireup="false" CodeFile="UserAddressList.ascx.vb" Inherits="UserControls_AddressList" %>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TalentEBusinessDBConnectionString %>"
    SelectCommand="SELECT * FROM tbl_address WHERE PARTNER=@PARTNER AND LOGINID=@LOGINID ORDER BY SEQUENCE ">
    <SelectParameters>
        <asp:QueryStringParameter DefaultValue="0" Name="PARTNER" QueryStringField="pa"
            Type="String" />
        <asp:QueryStringParameter DefaultValue="0" Name="LOGINID" QueryStringField="lo"
            Type="String" />
    </SelectParameters>
    </asp:SqlDataSource>
<table>
    <tr>
        <td>
            <div id="Maintenance">
                <asp:GridView ID="grdDataTable" DataKeyNames="ADDRESS_ID" DataSourceID="SqlDataSource1"
                    AutoGenerateColumns="False" runat="server" AllowPaging="True" AllowSorting="True"
                    PageSize="20" PagerSettings-Mode="NextPreviousFirstLast" PagerSettings-Position="Bottom"
                    PagerStyle-HorizontalAlign="Right" Caption="<h2>User Maintenance</h2>" CaptionAlign="Left"
                    SelectedRowStyle-BackColor="#eeeeee" CellPadding="1" CellSpacing="1" HorizontalAlign="Left"
                    AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false">
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField SortExpression="ADDRESS_ID" DataField="ADDRESS_ID" ReadOnly="True"
                            HeaderText=" ID " />
                        <asp:BoundField SortExpression="PARTNER" DataField="PARTNER" HeaderText=" Partner " />
                        <asp:BoundField SortExpression="LOGINID" DataField="LOGINID" HeaderText=" Login Id " />
                        <asp:BoundField SortExpression="TYPE" DataField="TYPE" HeaderText="Type" />
                        <asp:BoundField SortExpression="REFERENCE" DataField="REFERENCE" HeaderText="Reference" />
                        <asp:BoundField SortExpression="SEQUENCE" DataField="SEQUENCE" HeaderText="Sequence" />
                        <asp:BoundField SortExpression="DEFAULT_ADDRESS" DataField="DEFAULT_ADDRESS" HeaderText="Default" />
                        <asp:BoundField SortExpression="ADDRESS_LINE_1" DataField="ADDRESS_LINE_1" HeaderText="Address" />
                        <asp:BoundField SortExpression="ADDRESS_LINE_2" DataField="ADDRESS_LINE_2" HeaderText="Line 2" />
                        <asp:BoundField SortExpression="ADDRESS_LINE_3" DataField="ADDRESS_LINE_3" HeaderText="Line 3" />
                        <asp:BoundField SortExpression="ADDRESS_LINE_4" DataField="ADDRESS_LINE_3" HeaderText="Line 4" />
                        <asp:BoundField SortExpression="ADDRESS_LINE_5" DataField="ADDRESS_LINE_3" HeaderText="Line 5" />
                    </Columns>
                </asp:GridView>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <br />
            <br />
            <br />
            <div id="User2" class="User box2" runat="server">
                <asp:Button ID="cmdEdit" runat="server" Text="Edit" />
                <asp:Button ID="cmdDelete" runat="server" Text="Delete" />
                <asp:Button ID="cmdInsert" runat="server" Text="Insert" />
            </div>
        </td>
    </tr>
</table>
