<%@ Control Language="VB" AutoEventWireup="false" CodeFile="UserList.ascx.vb" Inherits="UserControls_UserList" %>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TalentEBusinessDBConnectionString %>"
    SelectCommand="SELECT * FROM tbl_authorized_users 
                        WHERE BUSINESS_UNIT=@BUSINESS_UNIT 
                        AND PARTNER=@PARTNER 
                        ORDER BY BUSINESS_UNIT, PARTNER, LOGINID ">
    <SelectParameters>
        <asp:QueryStringParameter DefaultValue="*" Name="BUSINESS_UNIT" QueryStringField="bu"
            Type="String" />
        <asp:QueryStringParameter DefaultValue="*" Name="PARTNER" QueryStringField="pa"
            Type="String" />
    </SelectParameters>
</asp:SqlDataSource>
<asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:TalentEBusinessDBConnectionString %>"
    SelectCommand="SELECT * FROM tbl_bu ORDER BY BUSINESS_UNIT">
</asp:SqlDataSource>
<asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:TalentEBusinessDBConnectionString %>"
    SelectCommand="SELECT *  FROM tbl_partner ORDER BY PARTNER">
</asp:SqlDataSource>
<div id="Maintenance">
    <table>
        <tr>
            <td>
                <label for="BusinessUnit">
                    <asp:Label ID="lblBusinessUnit" runat="server">Business Unit</asp:Label></label>
                <asp:DropDownList ID="cboBusinessUnit" CssClass="select" runat="server" DataSourceID="SqlDataSource2"
                    DataTextField="BUSINESS_UNIT_DESC" DataValueField="BUSINESS_UNIT">
                </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td>
                <label for="Partner">
                    <asp:Label ID="lblPartner" runat="server">Partner</asp:Label></label>
                <asp:DropDownList ID="cboPartner" CssClass="select" runat="server" DataSourceID="SqlDataSource3"
                    DataTextField="PARTNER_DESC" DataValueField="PARTNER">
                </asp:DropDownList>
                <asp:Button ID="cmdGo" runat="server" Text="Go" />
            </td>
        </tr>
        <tr>
            <td>
                <asp:GridView ID="grdDataTable" DataKeyNames="AUTH_USERS_ID" DataSourceID="SqlDataSource1"
                    AutoGenerateColumns="False" runat="server" AllowPaging="True" AllowSorting="True"
                    PageSize="20" PagerSettings-Mode="NextPreviousFirstLast" PagerSettings-Position="Bottom"
                    PagerStyle-HorizontalAlign="Right" Caption="<h2>User Maintenance</h2>" CaptionAlign="Left"
                    SelectedRowStyle-BackColor="#eeeeee" CellPadding="1" CellSpacing="1" HorizontalAlign="Left"
                    AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false">
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField SortExpression="AUTH_USERS_ID" DataField="AUTH_USERS_ID" ReadOnly="True"
                            HeaderText=" ID " />
                        <asp:BoundField SortExpression="BUSINESS_UNIT" DataField="BUSINESS_UNIT" HeaderText=" Business unit " />
                        <asp:BoundField SortExpression="PARTNER" DataField="PARTNER" HeaderText=" Partner " />
                        <asp:BoundField SortExpression="LOGINID" DataField="LOGINID" HeaderText=" Login Id " />
                        <asp:BoundField SortExpression="IS_LOCKED_OUT" DataField="IS_LOCKED_OUT" HeaderText=" Locked Out" />
                        <asp:BoundField SortExpression="LAST_LOGIN_DATE" DataField="LAST_LOGIN_DATE" HeaderText=" Last Logon " />
                    </Columns>
                    <PagerSettings Mode="NextPreviousFirstLast" />
                    <SelectedRowStyle BackColor="#EEEEEE" />
                    <PagerStyle HorizontalAlign="Right" />
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <td>
                <br />
                <br />
                <br />
                <div id="User2" class="User box2" runat="server">
                    <asp:Button ID="cmdEdit" runat="server" Text="Edit" />
                    <asp:Button ID="cmdDelete" runat="server" Text="Delete" />
                    <asp:Button ID="cmdInsert" runat="server" Text="Insert" />
                    <asp:Button ID="cmdAddress" runat="server" Text="Address" />
                </div>
            </td>
        </tr>
    </table>
</div>
