-- =============================================
-- Ensure BCT_URL and BCT_PARENT are formatted correctly
-- =============================================
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/UserControlled/AboutUs.aspx' WHERE [PAGE_CODE] = 'AboutUs.aspx'										
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/UserControlled/Accessibility.aspx' WHERE [PAGE_CODE] = 'Accessibility.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Smartcard/ActivateSmartcard.aspx' WHERE [PAGE_CODE] = 'ActivateSmartcard.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/Agent/AgentLogin.aspx' WHERE [PAGE_CODE] = 'AgentLogin.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/AmendPPSEnrolment.aspx' WHERE [PAGE_CODE] = 'AmendPPSEnrolment.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/AmendPPSPayments.aspx' WHERE [PAGE_CODE] = 'AmendPPSPayments.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '	~/PagesPublic/Basket/Basket.aspx' WHERE [PAGE_CODE] = 'Basket.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'orderEnquiry.aspx', [BCT_URL] = '~/PagesLogin/Orders/CATConfirm.aspx' WHERE [PAGE_CODE] = 'CATConfirm.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Basket.aspx', [BCT_URL] = '~/PagesLogin/Checkout/Checkout.aspx' WHERE [PAGE_CODE] = 'Checkout.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/Contact/ContactUs.aspx' WHERE [PAGE_CODE] = 'contactUs.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'contactUs.aspx', [BCT_URL] = '~/PagesPublic/Contact/ContactUsConfirmation.aspx' WHERE [PAGE_CODE] = 'ContactUsConfirmation.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'CustomerSelection.aspx', [BCT_URL] = '~/PagesAgent/Profile/CourseDetails.aspx' WHERE [PAGE_CODE] = 'CourseDetails.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/Profile/CustomerSelection.aspx' WHERE [PAGE_CODE] = 'CustomerSelection.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'CustomerSelection.aspx', [BCT_URL] = '~/PagesAgent/Profile/DirectDebitDetails.aspx' WHERE [PAGE_CODE] = 'DirectDebitDetails.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'CustomerSelection.aspx', [BCT_URL] = '~/PagesAgent/Orders/EndOfDay.aspx' WHERE [PAGE_CODE] = 'EndOfDay.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Smartcard/EPurse.aspx' WHERE [PAGE_CODE] = 'EPurse.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = '', [BCT_URL] = '' WHERE [PAGE_CODE] = 'error.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Profile/FavouriteSeat.aspx' WHERE [PAGE_CODE] = 'FavouriteSeat.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '	~/PagesPublic/Profile/ForgottenPassword.aspx' WHERE [PAGE_CODE] = 'forgottenPassword.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'forgottenPassword.aspx', [BCT_URL] = '~/PagesPublic/Profile/ForgottenPasswordConfirmation.aspx' WHERE [PAGE_CODE] = 'forgottenPasswordConfirmation.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/FriendsAndFamily/FriendsAndFamily.aspx' WHERE [PAGE_CODE] = 'FriendsAndFamily.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = '', [BCT_URL] = '' WHERE [PAGE_CODE] = 'home.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'LinkedProducts.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Login.aspx', [BCT_URL] = '~/PagesPublic/Login/LoggedOut.aspx' WHERE [PAGE_CODE] = 'LoggedOut.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/Login/Login.aspx' WHERE [PAGE_CODE] = 'login.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/MatchDayHospitality.aspx' WHERE [PAGE_CODE] = 'MatchDayHospitality.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesLogin/Profile/myAccount.aspx' WHERE [PAGE_CODE] = 'myAccount.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Profile/OnAccount.aspx' WHERE [PAGE_CODE] = 'OnAccount.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Orders/orderEnquiry.aspx' WHERE [PAGE_CODE] = 'orderDetails.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'orderEnquiry.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'OrderReturn.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'OrderReturnConfirmation.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Orders/OrderReturnEnquiry.aspx' WHERE [PAGE_CODE] = 'OrderReturnEnquiry.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/ProductAway.aspx' WHERE [PAGE_CODE] = 'productAway.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/ProductEvent.aspx' WHERE [PAGE_CODE] = 'ProductEvent.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/ProductHome.aspx' WHERE [PAGE_CODE] = 'productHome.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/ProductMembership.aspx' WHERE [PAGE_CODE] = 'productMembership.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/ProductSeason.aspx' WHERE [PAGE_CODE] = 'ProductSeason.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/ProductSubTypes.aspx' WHERE [PAGE_CODE] = 'ProductSubTypes.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/ProductBrowse/ProductTravel.aspx' WHERE [PAGE_CODE] = 'ProductTravel.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Profile/ProfilePhoto.aspx' WHERE [PAGE_CODE] = 'ProfilePhoto.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'updateProfile.aspx', [BCT_URL] = '~/PagesAgent/Profile/PromotionHistory.aspx' WHERE [PAGE_CODE] = 'Promotionhistory.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Promotionhistory.aspx	', [BCT_URL] = '' WHERE [PAGE_CODE] = 'PromotionhistoryDetail.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesPublic/Profile/Registration.aspx' WHERE [PAGE_CODE] = 'registration.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'registration.aspx', [BCT_URL] = '~/PagesPublic/Profile/RegistrationConfirmation.aspx' WHERE [PAGE_CODE] = 'registrationConfirmation.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'RegistrationParticipants.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Profile/SaveMyCard.aspx' WHERE [PAGE_CODE] = 'SaveMyCard.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'orderEnquiry.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'SeatHistory.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'orderEnquiry.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'SeatPrintHistory.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = '', [BCT_URL] = ''	 WHERE [PAGE_CODE] = 'seatSelection.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'standAndAreaSelection.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'updateProfile.aspx', [BCT_URL] = '~/PagesAgent/Profile/StopCodeAudit.aspx' WHERE [PAGE_CODE] = 'StopCodeAudit.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'CustomerSelection.aspx', [BCT_URL] = '~/PagesAgent/Orders/TicketCollection.aspx' WHERE [PAGE_CODE] = 'TicketCollection.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'TicketingBrowse.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'ProductSeason.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'TicketingPrePayments.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'TransactionDetails.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesLogin/Orders/TransactionEnquiry.aspx' WHERE [PAGE_CODE] = 'TransactionEnquiry.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'MyAccount.aspx', [BCT_URL] = '~/PagesLogin/Profile/updateProfile.aspx' WHERE [PAGE_CODE] = 'updateProfile.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'updateProfile.aspx', [BCT_URL] = '~/PagesLogin/Profile/updateProfileConfirmation.aspx' WHERE [PAGE_CODE] = 'updateProfileConfirmation.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '~/PagesLogin/Profile/ValidatePassword.aspx' WHERE [PAGE_CODE] = 'ValidatePassword.aspx'
UPDATE [tbl_page] SET [BCT_PARENT] = 'Home.aspx', [BCT_URL] = '' WHERE [PAGE_CODE] = 'VisualSeatSelection.aspx'