DECLARE @ID BIGINT
SET @ID = 0;
DECLARE @BUSINESSUNITS_TABLE TABLE
(
 ID INT IDENTITY(1,1),
 BUSINESS_UNIT VARCHAR(50)
);
INSERT INTO @BUSINESSUNITS_TABLE (BUSINESS_UNIT)
(SELECT DISTINCT BUSINESS_UNIT FROM tbl_url_bu
UNION
SELECT DISTINCT BUSINESS_UNIT_FOR_CONTENT FROM tbl_url_bu)
WHILE EXISTS(SELECT * FROM @BUSINESSUNITS_TABLE WHERE ID > @ID)
BEGIN
	DECLARE @BUSINESS_UNIT varchar(100)
	SELECT TOP 1  @ID = ID, @BUSINESS_UNIT = BUSINESS_UNIT FROM @BUSINESSUNITS_TABLE WHERE ID > @ID ORDER BY ID ASC
	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'BOOKING' AND FEE_APPLY_TYPE = 7)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'BOOKING', 7, 'CHARGE_ALL', 'CHARGE_ALL, HIGHEST_ONLY, FIRST_ONLY', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'ADHOC' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'ADHOC', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'BOOKING' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'BOOKING', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'DIRECTDEBT' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'DIRECTDEBT', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'FINANCE' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'FINANCE', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'CANCEL' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'CANCEL', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'AMEND' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'AMEND', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'TRANSFER' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'TRANSFER', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'FULFILMENT' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'FULFILMENT', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'WEBSALES' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'WEBSALES', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

	IF NOT EXISTS(SELECT * FROM tbl_fees_relations WHERE BUSINESS_UNIT = @BUSINESS_UNIT AND [PARTNER] = '*ALL' AND FEE_CODE = 'DUMMY' AND FEE_CATEGORY = 'SUPPLYNET' AND FEE_APPLY_TYPE = 6)
	BEGIN
		INSERT INTO tbl_fees_relations (BUSINESS_UNIT, [PARTNER], FEE_CODE, FEE_CATEGORY, FEE_APPLY_TYPE, APPLY_RELATED_CODE, APPLY_RELATED_CODE_DESCRIPTION, ACTIVE)
			VALUES (@BUSINESS_UNIT, '*ALL', 'DUMMY', 'SUPPLYNET', 6, 'STANDARD', 'STANDARD, *ALL, TRAN_TYPE, PROD_TYPE, TKT_TYPE, TRAN_PROD_TYPE, TRAN_TKT_TYPE, PROD_TKT_TYPE', 1)
	END

END